
#ifndef DWM_CONFIG_COLORS_H
#define DWM_CONFIG_COLORS_H

#define BG_TRANSPARENCY "F0"

#define COL_TRANSPARENT ("#00000000")
#define COL_NORMAL_TEXT ("#FFBBBBBB")
#define COL_DARK_TEXT ("#FF0D1821")

#define COL_OK ("#" BG_TRANSPARENCY "2CA58D")
#define COL_WARN ("#" BG_TRANSPARENCY "FBAF00")
#define COL_DANGER ("#" BG_TRANSPARENCY "D81159")

#define COL_DARK_BG ("#" BG_TRANSPARENCY "0D1821")
#define COL_DARK_HIGHLIGHT_PRIMARY ("#" BG_TRANSPARENCY "222E50")
#define COL_DARK_HIGHLIGHT_SECONDARY ("#" BG_TRANSPARENCY "274690")

#endif // !DWM_CONFIG_COLORS_H
